version: "3.7"

services:
  api:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/server
    ports:
      - 8000:8000
